### ISSUE TITLE
Not working on 0.4.0

### ISSUE THREAD

**Issue by jankolkmeier** [mauricemach/coffeekup#25]
Tried on fresh ubuntu 10.10 using node.js 0.4.0, installed with npm.
Running $coffeekup fails with this:
    Error: Cannot find module 'coffeekup'
        at Function._resolveFilename (module.js:289:11)
        at Function._load (module.js:241:25)
        at require (module.js:317:19)
        at Object.<anonymous> (/usr/local/lib/node/.npm/coffeekup/0.2.2/package/bin/coffeekup.coffee:3:15)
        at Object.<anonymous> (/usr/local/lib/node/.npm/coffeekup/0.2.2/package/bin/coffeekup.coffee:76:4)
        at Module._compile (module.js:373:26)
        at Object.run (/usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/coffee-script.js:55:19)
        at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:115:29
        at /usr/local/lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:85:26
        at [object Object].<anonymous> (fs.js:86:5)

Trying to require it as module gives similar output.

**Comment by UnderCooled** [comment]
Add this line to `/usr/local/lib/node/.npm/coffeekup/active/package/package.json` :

```
"main": "./lib/index.js",
```

**Comment by jankolkmeier** [comment]
Works great, thanks!

**Comment by quickredfox** [comment]
Above "fix" does not work for me on Node 0.4.2 with coffeekup 0.2.2

**Comment by hackervera** [comment]
that fixed it for me. thanks
