### ISSUE TITLE
npm failed to require 'coffeekup'

### ISSUE THREAD

**Issue by pyrostrex** [mauricemach/coffeekup#28]

**Comment by davidarkemp** [comment]
```
# npm install coffeekup

# coffee
```

   coffee> coffeekup = require 'coffeekup'

```
Error: Cannot find module 'coffeekup'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (test.coffee:2:3)
    at Object.<anonymous> (test.coffee:3:4)
    at Module._compile (module.js:404:26)
    at Object.run (.../lib/node/.npm/coffee-script/1.0.1/package/lib/coffee-script.js:55:19)
    at .../lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:115:29
    at .../lib/node/.npm/coffee-script/1.0.1/package/lib/command.js:85:26
    at [object Object].<anonymous> (fs.js:107:5)
```

**Comment by alduro** [comment]
I have exactly the same problem.

**Comment by valpackett** [comment]
Me too :(

**Comment by quickredfox** [comment]
Temporary Solution, Add: 

```
  "main": "./lib/index"
```

To package.json... it's been mentioned before and i think there's a patch in one of the pull requests.

**Comment by alduro** [comment]
ok, it worked!
aldo@macbook ~/local/node/lib/node/.npm/coffeekup > node

> require('coffeekup')
> { version: '0.2.2',
>   compile: [Function],
>   render: [Function],
>   adapters: { simple: [Function], meryl: [Function] } }

and index.js has to be:
module.exports = require('./coffeekup')
and not ./lib/coffeekup

Thanks.

**Comment by alduro** [comment]
well, after upgrade npm to 1.0.3 and having installed modules under $HOME/local/node/lib/node_modules/coffeekup the error is back. Any clue ?

**Comment by quickredfox** [comment]
My guess would be to conduct an investigation on what has changed in the commonJS packages spec and/or how node's "require" follows those changes or not /w regards to what npm also has to say on that. This was the general path I took to figuring it out the last time, it seems to be as it's just a "living on the edge" kinda bug.

**Comment by alduro** [comment]
installing coffeekup locally works fine. The problem is when is installed globally.

**Comment by mauricemach** [comment]
Tested the patch on two machines and still got the issue with or without it. Actually I can't require anything inside the coffee REPL, unless installed globally (in which case even coffeekup works without the patch). Requiring local packages inside the node REPL always works, coffeekup included.

OS: OS X 10.6.8 / Ubuntu 11.04
node: 0.4.8 / 0.4.9
coffeescript: 1.1.1 (both)
npm: 1.0.15 (both)

Jason, does the fix still work for you? How's your environment?

**Comment by mauricemach** [comment]
Closing since it seems to be fixed in current versions of npm, feel free to reopen if it happens again to you.
