### ISSUE TITLE
coffeekup cli not working with coffeescript 1.2

### ISSUE THREAD

**Issue by dubiousdavid** [mauricemach/coffeekup#106]
Error: Cannot find module 'coffee-script/lib/optparse'

Should be 'coffee-script/lib/coffee-script/optparse' or 'coffee-script/optparse'.  Not sure.  I'm new to npm and node.  Either way the path is wrong.

**Comment by reaktivo** [comment]
Getting this too.

**Comment by vayn** [comment]
I've got the same issue.

**Comment by flosse** [comment]
me too :-/

**Comment by avioli** [comment]
a nasty workaround hack:

**Note**: do a `npm update` or `npm -g update`, just to be sure you are up to date (use -g to do a global update)

go to your coffeekup instance (`npm -g install coffeekup` installs it under /usr/local/lib/node_modules/coffeekup/)
`cd lib/`
and open **cli.js** with your fav text editor.

change this line (#7):

```
  OptionParser = require('coffee-script/lib/optparse').OptionParser;
```

into

```
  OptionParser = require('coffee-script/lib/coffee-script/optparse').OptionParser;
```

works for me. hope it helps someone else as well.

**Comment by gradus** [comment]
I had run into this problem too. Have it marked as an issue to resolve in my own version that I started since it looks like this one is not being maintained, but installing optparse globally fixes the problem with CoffeeCup which should work just like CoffeeKup with a minor name change.  I will be actively maintaining it and addressing issues (hopefully w/ some help)

https://github.com/gradus/coffeecup/issues/2

https://github.com/gradus/coffeecup

**Comment by gradus** [comment]
This issue is fixed in my clone of coffeekup.

https://github.com/gradus/coffeecup

**Comment by flowerornament** [comment]
avioli's hack worked for me for now

**Comment by avioli** [comment]
@msutherl if you clone coffeecup, not coffeekup (a k difference) as @gradus says you won't need to do my hack, because he fixed it in his clone.

**Comment by gradus** [comment]
@msutherl @gradus https://github.com/gradus/coffeecup is being actively maintained.  The current version of CoffeeCup v0.3.5-3 is compatible with the latest stable node and coffeescript versions. 0.6.12 and 1.2.0 respectively.  I am working on a few new features and some small fixes. Should be releasing a new version soon.

**Comment by Itja** [comment]
I don't know how exactly i ran into this problem 3 years later (using only npm packages), but another workaround for this is 
cd /usr/local/lib/node_modules/coffee-script/lib
ln -s coffee-script/optparse.js optparse.js
